sudo: false
language: python
python:
  - 3.5
  - 3.6
matrix:
  include:
    - python: 3.7
      dist: xenial  # Required for Python 3.7
      sudo: true    # Required for Python 3.7
install:
  - pip install poetry
  - poetry install -vvv
script:
  - poetry run
  - poetry run coverage run --source=hogwarts-apitest -m pytest -v
#after_success:
#  - poetry run coveralls